# Use latest node version 12.16.1
FROM node:12-alpine

# set /server directory as default working directory
WORKDIR /server

# only copy package.json and package-lock.json
# if there are changes in package.json
ADD package*.json /server/

# install production packages
RUN npm install --production

# copy all file from current dir to /server in container
COPY . .

# expose port 4040
EXPOSE 4040

# cmd to start service
CMD [ "npm", "start" ]
